version: "3.9"

services:
  vanilla:
    build:
      dockerfile: Dockerfile
    env_file: .env
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/app
      - ./localdata/log:/usr/log
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13.5-alpine3.15
    volumes:
      - ./localdata/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
